name: Selenium Tests

run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches:
      - master
      - 25-setup-github-actions-workflow
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version: '22'
          cache: 'maven'
      - name: Set up Chrome
        uses: actions/setup-chrome@v2
      - name: Set up Firefox
        uses: actions/setup-firefox@v2
      - name: Set up Edge
        uses: actions/setup-edge@v1
      - name: Build with Maven, run tests
        run: mvn -B package --file pom.xml