name: Selenium Tests

run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches:
      - master
      - 25-setup-github-actions-workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'pom.xml'
      - name: Build with Maven
        run: mvn -B clean package

      - name: Run Selenium Tests
        run: mvn test

