name: Selenium Tests

run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches:
      - master
      - 25-setup-github-actions-workflow
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version: '22'
          cache: 'maven'
      - name: Install Chrome and ChromeDriver
        run: |
          LATEST_CHROME=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -q -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$LATEST_CHROME/chromedriver_linux64.zip
          unzip -q /tmp/chromedriver.zip -d /tmp
          sudo mv /tmp/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      - name: Build with Maven, run tests
        run: mvn -B package --file pom.xml